on: push
name: ðŸŒˆ Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2

    - name: ðŸ§° Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: ðŸ›  Build Project
      run: |
        npm install
        npm run build
    
    - name: ðŸ”„ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
          404.html
        local-dir: ./dist/
        server-dir: bhdzllr/
        state-name: .sync-state.json
        dry-run: false
